services:
  webapi:
    #restart: on-failure  
    build:
      context: .
      target: final
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy   
    environment:
        - ConnectionStrings_Default=User ID=postgres;Password=As30101987;Server=db;Port=5432;Database=DemoDatabase;        
  db:
    image: postgres:16.2
    restart: always
    # volumes:
    #    - db-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: As30101987
        POSTGRES_DB: DemoDatabase
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
# volumes:
#    db-data:
  
# ???? volumes ????????? ??? ????. ?.?. ??? ????????? ??????? ??? ????????????? ???????? ?????? ???? ???????? ?? ??????.
# ??? ??????? ???????????? ???????????.
# ????? ??????????? ??, ????? ???????????? ??????